CRITICAL = 'CRITICAL'
WARNING = 'WARNING'
ATTENTION = 'ATTENTION'
PRICE = "price"
REFILLABITILITY = "refillability"
ALLOW_ITEMS = "allowed_items"
SELF_PERSON_NAME = "self_name"
MONEY = "money"
PRIMARY_KEY = "PRIMARY KEY"
PARAMS = 'parameters'
DEFAULT = 'default'
KEY = 'key'
FIRST_SPAWN = "FIRST SPAWN"
SELECT_ITEM = "selected_item"
PRIORITY = "priority"
MAX_RSTR = "max_need"
EXPENDITURE = "cost_per_hour"
EXPENDITURE_DAY = "cost_per_day"
CONDITION = "if"
NAME = "name"
HISTORY = "history"
SELECT = "selected"
TRANSLATE_INFO = "tr_info"
